/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-tint": "var(--surface-tint)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container-highest": "var(--surface-container-highest)",
        tertiary: "var(--tertiary)",
        "surface-container-low": "var(--surface-container-low)",
        "on-background": "var(--on-background)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        outline: "var(--outline)",
        "on-error-container": "var(--on-error-container)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "secondary-container": "var(--secondary-container)",
        surface: "var(--surface)",
        "surface-deep": "var(--surface-deep)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-primary": "var(--on-primary)",
        "on-error": "var(--on-error)",
        "outline-variant": "var(--outline-variant)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-container": "var(--surface-container)",
        "inverse-surface": "var(--inverse-surface)",
        "primary-fixed": "var(--primary-fixed)",
        "slate-muted": "var(--slate-muted)",
        "surface-glass": "var(--surface-glass)",
        "inverse-primary": "var(--inverse-primary)",
        secondary: "var(--secondary)",
        primary: "var(--primary)",
        "on-tertiary": "var(--on-tertiary)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-bright": "var(--surface-bright)",
        error: "var(--error)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-variant": "var(--surface-variant)",
        "error-container": "var(--error-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-secondary": "var(--on-secondary)",
        "primary-container": "var(--primary-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
      },
      backgroundImage: {
        "electric-glow": "var(--electric-glow)",
        "success-glow": "linear-gradient(135deg, #10B981 0%, #059669 100%)",
      },
      borderRadius: {
        xxl: "1.5rem",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        ui: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        reading: ['"Source Sans 3"', "Segoe UI", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
