/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#111125",
        "on-primary-fixed-variant": "#6700b5",
        "surface-dim": "#111125",
        "surface-container-high": "#28283d",
        "on-secondary-container": "#00311f",
        "surface-tint": "#dcb8ff",
        "tertiary-container": "#935400",
        "surface-container-highest": "#333348",
        tertiary: "#ffb873",
        "surface-container-low": "#1a1a2e",
        "on-background": "#e2e0fc",
        "inverse-on-surface": "#2f2e43",
        outline: "#988ca0",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#2c0051",
        "surface-container-lowest": "#0c0c1f",
        "on-secondary-fixed": "#002113",
        "secondary-container": "#00a572",
        surface: "#111125",
        "surface-deep": "#0F0F1E",
        "on-tertiary-container": "#ffdaba",
        "on-secondary-fixed-variant": "#005236",
        "on-primary": "#480081",
        "on-error": "#690005",
        "outline-variant": "#4c4354",
        "on-surface": "#e2e0fc",
        "on-surface-variant": "#cfc2d7",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#1e1e32",
        "inverse-surface": "#e2e0fc",
        "primary-fixed": "#efdbff",
        "slate-muted": "#94A3B8",
        "surface-glass": "rgba(26, 26, 46, 0.7)",
        "inverse-primary": "#8422dc",
        secondary: "#4edea3",
        primary: "#dcb8ff",
        "on-tertiary": "#4b2800",
        "on-tertiary-fixed": "#2d1600",
        "on-primary-container": "#eed9ff",
        "primary-fixed-dim": "#dcb8ff",
        "surface-bright": "#37374d",
        error: "#ffb4ab",
        "tertiary-fixed": "#ffdcbf",
        "surface-variant": "#333348",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-secondary": "#003824",
        "primary-container": "#8a2be2",
        "tertiary-fixed-dim": "#ffb873",
      },
      backgroundImage: {
        "electric-glow": "linear-gradient(135deg, #8A2BE2 0%, #4B0082 100%)",
        "success-glow": "linear-gradient(135deg, #10B981 0%, #059669 100%)",
      },
      borderRadius: {
        xxl: "1.5rem",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-lg": ["Sora", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
